"""init

Revision ID: 8d4bbc64aa04
Revises: 
Create Date: 2022-07-17 14:36:54.136893

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8d4bbc64aa04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('event_result_id', sa.Integer(), nullable=False),
    sa.Column('score_index', sa.Integer(), nullable=False),
    sa.Column('score1', sa.Integer(), nullable=False),
    sa.Column('score2', sa.Integer(), nullable=False),
    sa.Column('flags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('new', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
